# run_minpub.py
# Minimal publishable run: run paper_run.py then paper_analyze_plus.py then paper_significance.py
# Uses sys.executable so it always uses the current conda env python.

import os, sys, argparse, subprocess

def run(cmd, cwd):
    print("\nCMD:", " ".join(cmd))
    p = subprocess.run(cmd, cwd=cwd)
    if p.returncode != 0:
        raise SystemExit(p.returncode)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data_root", type=str, required=True)
    ap.add_argument("--unknown_k", type=int, default=2)
    ap.add_argument("--num_splits", type=int, default=5)      # keep small but still report mean±std
    ap.add_argument("--seeds", type=str, default="0,1")       # 2 seeds = shortest publishable path
    ap.add_argument("--include_energy", action="store_true")
    args = ap.parse_args()

    code_dir = os.path.dirname(os.path.abspath(__file__))
    py = sys.executable  # current env python

    paper_run = os.path.join(code_dir, "paper_run.py")
    paper_analyze = os.path.join(code_dir, "paper_analyze_plus.py")
    paper_sig = os.path.join(code_dir, "paper_significance.py")

    if not os.path.exists(paper_run):
        raise SystemExit(f"Not found: {paper_run}")
    if not os.path.exists(paper_analyze):
        raise SystemExit(f"Not found: {paper_analyze}")

    # 1) run experiments
    cmd1 = [
        py, paper_run,
        "--data_root", args.data_root,
        "--unknown_k", str(args.unknown_k),
        "--num_splits", str(args.num_splits),
        "--seeds", args.seeds,
    ]
    if args.include_energy:
        cmd1.append("--include_energy")
    run(cmd1, cwd=code_dir)

    # paper_run.py prints the out_dir, but we can also infer "latest results dir"
    results_root = os.path.join(code_dir, "results")
    if not os.path.isdir(results_root):
        raise SystemExit(f"Not found results folder: {results_root}")

    subdirs = [os.path.join(results_root, d) for d in os.listdir(results_root)]
    subdirs = [d for d in subdirs if os.path.isdir(d)]
    subdirs.sort(key=lambda x: os.path.getmtime(x), reverse=True)
    out_dir = subdirs[0]

    results_csv = os.path.join(out_dir, "results.csv")
    if not os.path.exists(results_csv):
        raise SystemExit(f"Not found: {results_csv}")

    # 2) analyze to tables (macro, best_by_target, paired deltas, etc.)
    run([py, paper_analyze, "--results_csv", results_csv, "--std", "sample"], cwd=code_dir)

    # 3) significance from paired deltas (requires paired_delta_vs_baseline.csv already generated by analyze_plus)
    paired_csv = os.path.join(out_dir, "paired_delta_vs_baseline.csv")
    if os.path.exists(paired_csv) and os.path.exists(paper_sig):
        run([py, paper_sig, "--paired_csv", paired_csv], cwd=code_dir)
    else:
        print("[WARN] paired_delta_vs_baseline.csv or paper_significance.py missing; skip significance.")

    print("\n[OK] Paper-ready outputs are in:\n ", out_dir)

if __name__ == "__main__":
    main()
